version: "2"
services:
  mongo:
    image: "mongo:3.4"
    ports:
      - "27017:27017"
  api:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - 4000:4000
    depends_on:
      - mongo
    command: sh start.sh
